#!/usr/bin/env bash
set -euo pipefail

tag="${1:?release tag is required}"
dist="${2:?artifact directory is required}"
output="${3:?formula output path is required}"
version="${tag#v}"

if [[ "$tag" != v* || -z "$version" ]]; then
  echo "release tag must start with v" >&2
  exit 2
fi

checksum() {
  local target="$dist/waybend-$tag-$1.tar.gz"
  if [[ ! -f "$target" ]]; then
    echo "missing release artifact: $target" >&2
    exit 2
  fi
  sha256sum "$target" | awk '{print $1}'
}

linux_amd64="$(checksum x86_64-unknown-linux-musl)"
linux_arm64="$(checksum aarch64-unknown-linux-musl)"
macos_amd64="$(checksum x86_64-apple-darwin)"
macos_arm64="$(checksum aarch64-apple-darwin)"

mkdir -p "$(dirname "$output")"
cat >"$output" <<RUBY
# typed: false
# frozen_string_literal: true

# Generated by Waybend's release workflow. DO NOT EDIT.
class Waybend < Formula
  desc "Self-hosted SSRF redirect, payload, callback, and DNS workbench"
  homepage "https://principlebreach.com"
  version "$version"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/principlebreach/waybend/releases/download/$tag/waybend-$tag-x86_64-apple-darwin.tar.gz"
      sha256 "$macos_amd64"
    elsif Hardware::CPU.arm?
      url "https://github.com/principlebreach/waybend/releases/download/$tag/waybend-$tag-aarch64-apple-darwin.tar.gz"
      sha256 "$macos_arm64"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/principlebreach/waybend/releases/download/$tag/waybend-$tag-x86_64-unknown-linux-musl.tar.gz"
      sha256 "$linux_amd64"
    elsif Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/principlebreach/waybend/releases/download/$tag/waybend-$tag-aarch64-unknown-linux-musl.tar.gz"
      sha256 "$linux_arm64"
    end
  end

  def install
    bin.install "waybend"
    etc.install "waybend.example.yml" => "waybend.yml"
    (var/"lib/waybend").mkpath
  end

  service do
    run [opt_bin/"waybend", "serve", "--config", etc/"waybend.yml"]
    keep_alive true
    working_dir var/"lib/waybend"
    log_path var/"log/waybend.log"
    error_log_path var/"log/waybend.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/waybend version")
  end
end
RUBY
