const state={routes:[],events:[],eventTotal:0,eventLoad:0,eventTimer:null,capabilities:null,routeTokens:new Map(),token:sessionStorage.getItem('waybend-token')||'',routePage:1,routePageSize:12,eventPage:1,eventPageSize:10};
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const headers=()=>state.token?{Authorization:`Bearer ${state.token}`}:{},api=async path=>{const response=await fetch(path,{headers:headers()});if(response.status===401){$('#auth-dialog').showModal();throw new Error('Authentication required')}if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error?.message||`Request failed (${response.status})`);return response.json()};
function toast(text){const element=$('#toast');element.textContent=text;element.classList.add('show');setTimeout(()=>element.classList.remove('show'),1600)}
function randomToken(){const bytes=new Uint8Array(12);crypto.getRandomValues(bytes);return[...bytes].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
function routeToken(id){if(!state.routeTokens.has(id))state.routeTokens.set(id,randomToken());return state.routeTokens.get(id)}
function endpoint(route){return `${location.origin}/r/${encodeURIComponent(route.id)}/1?token=${routeToken(route.id)}`}
function paginate(rows,page,pageSize){const pages=Math.max(1,Math.ceil(rows.length/pageSize));const current=Math.min(Math.max(1,page),pages);const start=(current-1)*pageSize;return{rows:rows.slice(start,start+pageSize),current,pages,start,end:Math.min(start+pageSize,rows.length)}}
function setPagination(prefix,result,total){$(`#${prefix}-page-status`).textContent=total?`${result.start+1}–${result.end} of ${total}`:'0 results';$(`#${prefix}-prev`).disabled=result.current<=1;$(`#${prefix}-next`).disabled=result.current>=result.pages;$(`#${prefix}-pagination`).hidden=total===0}
function filteredRoutes(){const query=$('#route-search').value.toLowerCase().trim(),category=$('#category-filter').value;return state.routes.filter(route=>(!category||route.category===category)&&(!query||[route.id,route.title,route.description,route.target,route.category,...route.tags].join(' ').toLowerCase().includes(query)))}
function renderRoutes(){const rows=filteredRoutes(),result=paginate(rows,state.routePage,state.routePageSize);state.routePage=result.current;$('#route-count').textContent=`${rows.length} route${rows.length===1?'':'s'}`;$('#route-empty').hidden=rows.length>0;$('#route-grid').hidden=rows.length===0;$('#route-grid').innerHTML=result.rows.map(route=>{const waybendUrl=endpoint(route);return`<article class="card"><div class="card-head"><div><span class="category">${esc(route.category)}</span><h2>${esc(route.title)}</h2></div><span class="meta">${route.status} / ${route.hops} hop${route.hops===1?'':'s'}</span></div><p class="description">${esc(route.description||route.target)}</p><div class="route-value"><span>Terminal target</span><code title="${esc(route.target)}">${esc(route.target)}</code></div><div class="route-value"><span>Waybend URL</span><div class="endpoint"><code title="${esc(waybendUrl)}">${esc(waybendUrl)}</code><button class="copy" data-copy="${esc(waybendUrl)}" aria-label="Copy ${esc(route.title)} Waybend URL">Copy</button></div></div><div class="tags">${route.tags.map(tag=>`<span class="tag">${esc(tag)}</span>`).join('')}</div></article>`}).join('');setPagination('route',result,rows.length)}
function renderEvents(){const rows=state.events,pages=Math.max(1,Math.ceil(state.eventTotal/state.eventPageSize));state.eventPage=Math.min(Math.max(1,state.eventPage),pages);const start=(state.eventPage-1)*state.eventPageSize,result={rows,current:state.eventPage,pages,start,end:start+rows.length};$('#event-empty').hidden=state.eventTotal>0;$('#event-list').hidden=state.eventTotal===0;$('.event-table-head').hidden=state.eventTotal===0;$('#event-result-count').textContent=`${state.eventTotal} event${state.eventTotal===1?'':'s'}`;$('#event-list').innerHTML=rows.map(event=>`<article class="event" tabindex="0" role="button" aria-expanded="false"><span class="kind">${esc(event.kind)}</span><time datetime="${esc(event.received_at)}">${new Date(event.received_at).toLocaleString()}</time><span class="path">${esc(event.path||event.dns_name||event.route_id||'—')}</span><span class="source">${esc(event.source_ip)}</span><div class="details"><code>${esc(JSON.stringify(event,null,2))}</code><button class="copy" data-copy="${esc(JSON.stringify(event,null,2))}">Copy JSON</button></div></article>`).join('');$('#event-count').textContent=state.eventTotal;setPagination('event',result,state.eventTotal)}
async function loadRoutes(){const data=await api('/api/v1/routes');state.routes=Array.isArray(data)?data:data.routes||[];const categories=[...new Set(state.routes.map(route=>route.category))].sort();$('#category-filter').innerHTML='<option value="">All categories</option>'+categories.map(category=>`<option>${esc(category)}</option>`).join('');renderRoutes()}
async function loadEvents(){const request=++state.eventLoad,params=new URLSearchParams({limit:String(state.eventPageSize),offset:String((state.eventPage-1)*state.eventPageSize)}),query=$('#event-search').value.trim(),kind=$('#kind-filter').value;if(query)params.set('q',query);if(kind)params.set('kind',kind);const data=await api(`/api/v1/events?${params}`);if(request!==state.eventLoad)return;state.events=Array.isArray(data)?data:data.events||[];state.eventTotal=Array.isArray(data)?state.events.length:data.total||0;renderEvents()}
function scheduleEventLoad(){clearTimeout(state.eventTimer);state.eventTimer=setTimeout(()=>loadEvents().catch(error=>toast(error.message)),250)}
async function loadCapabilities(){const data=await api('/api/v1/capabilities');state.capabilities=data;$('#builder-status').value=String(data.default_status);$('#builder-hops').value=String(data.default_hops);$('#builder-hops').max=String(data.max_hops);$('#builder-hop-limit').textContent=`1–${data.max_hops}`;$('#builder-submit').disabled=data.dynamic_redirects===false;$('.hint').textContent=data.dynamic_redirects===false?'Dynamic redirects are disabled on this instance.':'Base64url path encoding preserves scheme casing, query strings, encoded bytes, and template variables.'}
async function checkHealth(){try{await api('/health/ready');$('#health').className='health ok';$('#health span').textContent='Ready'}catch(error){if(!error.message.includes('Authentication')){$('#health').className='health bad';$('#health span').textContent='Unavailable'}}}
$$('.nav').forEach(button=>button.addEventListener('click',()=>{$$('.nav').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.toggleAttribute('aria-current',active)});$$('.view').forEach(view=>view.hidden=view.id!==`${button.dataset.view}-view`);if(button.dataset.view==='evidence')loadEvents().catch(()=>{})}));
$('#route-search').addEventListener('input',()=>{state.routePage=1;renderRoutes()});$('#category-filter').addEventListener('change',()=>{state.routePage=1;renderRoutes()});$('#route-page-size').addEventListener('change',event=>{state.routePageSize=Number(event.target.value);state.routePage=1;renderRoutes()});$('#route-prev').addEventListener('click',()=>{state.routePage-=1;renderRoutes();$('#route-grid').scrollIntoView({block:'start'})});$('#route-next').addEventListener('click',()=>{state.routePage+=1;renderRoutes();$('#route-grid').scrollIntoView({block:'start'})});
$('#event-search').addEventListener('input',()=>{state.eventPage=1;scheduleEventLoad()});$('#kind-filter').addEventListener('change',()=>{state.eventPage=1;loadEvents().catch(error=>toast(error.message))});$('#event-page-size').addEventListener('change',event=>{state.eventPageSize=Number(event.target.value);state.eventPage=1;loadEvents().catch(error=>toast(error.message))});$('#event-prev').addEventListener('click',()=>{state.eventPage-=1;loadEvents().then(()=>$('#event-list').scrollIntoView({block:'start'})).catch(error=>toast(error.message))});$('#event-next').addEventListener('click',()=>{state.eventPage+=1;loadEvents().then(()=>$('#event-list').scrollIntoView({block:'start'})).catch(error=>toast(error.message))});
$('#refresh-events').addEventListener('click',()=>loadEvents().catch(error=>toast(error.message)));document.addEventListener('click',event=>{const copy=event.target.closest('[data-copy]');if(copy)navigator.clipboard.writeText(copy.dataset.copy).then(()=>toast('Copied'));const row=event.target.closest('.event');if(row&&!copy){row.classList.toggle('open');row.setAttribute('aria-expanded',String(row.classList.contains('open')))}});document.addEventListener('keydown',event=>{if(event.key==='/'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){event.preventDefault();($('.view:not([hidden]) input[type=search]')||$('#route-search')).focus()}if((event.key==='Enter'||event.key===' ')&&event.target.classList.contains('event')){event.preventDefault();event.target.classList.toggle('open');event.target.setAttribute('aria-expanded',String(event.target.classList.contains('open')))}});
$('#builder-form').addEventListener('submit',async event=>{event.preventDefault();try{const params=new URLSearchParams({target:$('#builder-target').value,status:$('#builder-status').value,hops:$('#builder-hops').value});const result=await api(`/api/v1/encode?${params}`),url=new URL(result.url,location.origin);url.searchParams.set('token',randomToken());$('#builder-url').textContent=url.toString();$('#builder-result').hidden=false}catch(error){toast(error.message)}});$('#copy-builder').addEventListener('click',()=>navigator.clipboard.writeText($('#builder-url').textContent).then(()=>toast('Copied')));$('#auth-form').addEventListener('submit',()=>{state.token=$('#auth-token').value;sessionStorage.setItem('waybend-token',state.token);setTimeout(()=>{loadRoutes().catch(error=>toast(error.message));loadCapabilities().catch(error=>toast(error.message));loadEvents().catch(()=>{});checkHealth()},0)});Promise.all([loadRoutes(),loadCapabilities(),checkHealth()]).catch(error=>toast(error.message));
